site_name: Peter Luro Personal Microsite
nav:
  - Home: index.md
  - Resume: ./img/Resume-2023.pdf
  - Contact: contact.md
  - Projects: Projects.md
  - Technologies: Technologies.md
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/paluro567/personal-website'

theme:
  name: material
  # extra_javascript:
  #   - site/Logging/elastic_logging.js


