site_name: Peter Luro
nav:
  - Home: index.md
  - Resume: ./img/Resume-2024.pdf
  - Contact: contact.md
  - Projects: Projects.md
  - Technologies: Technologies.md
  - Sitemap: sitemap.xml  # Add the sitemap file to your navigation

theme:
  name: material

extra:
  meta:
    title: "Peter Luro - personal portfolio"
    description: "Description of your MkDocs site - Peter Luro."
    keywords: "Peter Luro"
