site_name: Peter Luro Personal Microsite
nav:
  - Home: index.md
  - Contact: ./Contact.md
  - Projects: Projects.md
  - Resume: ./img/Resume-2023.pdf
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/paluro567/personal-website'

theme:
  name: material
