site_name: Peter Luro Personal Microsite
nav:
  - Home: index.md
  - Contact: videos.md
  - Contact: Projects.md
  - Resume: graph.md
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/paluro567/personal-website'

theme:
  name: material
